from tbutzer/conda-base

env tony 1.0
workdir /home

#copy environment.yml /home

#run conda config --add channels conda-forge --force && \
    #conda install -y mamba && \
    #mamba env update -n base --file environment.yml

